"""Reproduce three source-world headers offline using Python standard library.

All inputs are relative to this file. No aerial/PDF assets or external downloads
are needed. --check verifies the input and output hashes against the baseline.
"""
from pathlib import Path
import argparse
import hashlib
import json
import math

HERE = Path(__file__).resolve().parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output', type=Path, default=HERE / 'generated',
                    help='Output directory (default: generated next to script)')
parser.add_argument('--check', action='store_true',
                    help='Fail if any source/output hash differs from baseline')
args = parser.parse_args()
ROOT = HERE / 'data'
OUT = args.output
OUT.mkdir(parents=True, exist_ok=True)
R, RAD = 6378137.0, math.pi / 180
LON0, LAT0 = 127.0585674, 37.6564809


def read(name):
    return json.loads((ROOT / name).read_text(encoding='utf-8'))


def quote(value):
    return json.dumps(str(value), ensure_ascii=False)


def number(value):
    if value is None:
        return '-1.0f'
    try:
        value = float(value)
    except (TypeError, ValueError):
        return '-1.0f'
    assert math.isfinite(value)
    return f'{value:.6f}f'


def game(lon, lat):
    return ((lon-LON0)*RAD*R*math.cos(LAT0*RAD)+52,
            -(lat-LAT0)*RAD*R-60)


def geometry_vertices(geometry):
    if not geometry:
        return []
    c = geometry['coordinates']
    if geometry['type'] == 'Polygon':
        assert len(c) == 1, 'Do not silently drop polygon holes'
        c = c[0]
    elif geometry['type'] == 'Point':
        c = [c]
    return [game(*point) for point in c]


def array(name, cpp_type, lines):
    return f'inline constexpr std::array<{cpp_type}, {len(lines)}> {name} = {{{{\n' + ',\n'.join(lines) + '\n}};\n'


def prefix():
    return ('// GENERATED by generate_cpp_headers.py from saved source data.\n'
            '// No aerial images, synthetic geometry or guessed scoring triggers are embedded.\n'
            '#pragma once\n#include "dobong_source_world.h"\n\nnamespace dobong_source {\n')


course = read('course-observed.geojson')
course_vertices, course_rows = [], []
for f in course['features']:
    vertices = geometry_vertices(f['geometry'])
    p = f['properties']
    geom_type = f['geometry']['type'] if f['geometry'] else 'Unknown'
    course_rows.append('    {' + ', '.join([
        quote(f['id']), quote(p['kind']), f'GeometryType::{geom_type}',
        f'Quality::{p["grade"]}', str(len(course_vertices)), str(len(vertices)),
        number(p['source_accuracy_m'])]) + '}')
    course_vertices.extend(vertices)
text = prefix()
metadata=course['metadata']
provenance=(f'Esri Wayback release {metadata["wayback_release_date"]}, capture {metadata["source_capture_date"]}; '
            f'source accuracy {metadata["source_accuracy_m"]}m. Direct aerial manual trace after documented2022/2023 works; '
            'not surveyed or scoring-certified.2026 shadow limits current detail comparison.')
text += f'inline constexpr const char* kCourseProvenance = {quote(provenance)};\n'
text += f'inline constexpr const char* kCourseCaptureDate = {quote(metadata["source_capture_date"])};\n'
parking_count=sum(f['properties']['kind']=='parking_access_stall_footprint_observed' for f in course['features'])
assert parking_count==4, 'Review any topology change explicitly'
text += f'inline constexpr std::size_t kObservedParkingAccessCount = {parking_count};\n'
text += array('kCourseVertices', 'Point', [f'    {{{number(x)}, {number(z)}}}' for x, z in course_vertices])
text += array('kCourseFeatures', 'CourseFeature', course_rows)
text += '} // namespace dobong_source\n'
(OUT / 'dobong_observed_data.h').write_text(text, encoding='utf-8', newline='\n')

context = read('surroundings-source.geojson')
context_vertices, context_rows = [], []
for f in context['features']:
    p, g = f['properties'], f['geometry']
    tags = p['tags']
    kind = ('PowerTower' if tags.get('power') == 'tower' else
            'PowerLine' if tags.get('power') == 'line' else
            'Substation' if tags.get('power') == 'substation' else
            'Railway' if 'railway' in tags else
            'Road' if 'highway' in tags else
            'Building')
    vertices = geometry_vertices(g)
    context_rows.append('    {' + ', '.join([
        quote(f['id']), quote(tags.get('name', '')), quote(p['source_url']),
        f'ContextKind::{kind}', f'GeometryType::{g["type"]}',
        str(len(context_vertices)), str(len(vertices)), number(tags.get('height')),
        number(tags.get('building:levels')), number(tags.get('width')),
        number(tags.get('lanes')), number(tags.get('layer')),
        'true' if tags.get('railway') == 'disused' else 'false',
        quote(tags.get('end_date', ''))]) + '}')
    context_vertices.extend(vertices)
text = prefix()
text += 'inline constexpr const char* kContextAttribution = "OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright";\n'
text += array('kContextVertices', 'Point', [f'    {{{number(x)}, {number(z)}}}' for x, z in context_vertices])
text += array('kContextFeatures', 'ContextFeature', context_rows)
text += '} // namespace dobong_source\n'
(OUT / 'dobong_context_data.h').write_text(text, encoding='utf-8', newline='\n')

dem = read('terrain/game-dem-129x129.json')
text = prefix()
text += 'inline constexpr const char* kTerrainAttribution = "Mapzen; SRTM and GMTED2010 terrain data courtesy of the U.S. Geological Survey. Terrain Tiles accessed 2026-09-06 from https://registry.opendata.aws/terrain-tiles/.";\n'
text += f'inline constexpr int kDemWidth = {dem["width"]};\n'
text += f'inline constexpr int kDemHeight = {dem["height"]};\n'
text += f'inline constexpr float kDemStep = {number(dem["step_m"])};\n'
text += f'inline constexpr float kDemEastMin = {number(dem["east_min_m"])};\n'
text += f'inline constexpr float kDemNorthMax = {number(dem["north_max_m"])};\n'
text += f'inline constexpr float kDemBaseElevation = {number(dem["base_elevation_m"])};\n'
values = dem['height_relative_m_row_major']
assert len(values) == dem['width'] * dem['height']
text += f'inline constexpr std::array<float, {len(values)}> kDemRelativeMeters = {{{{\n'
text += '\n'.join('    ' + ', '.join(number(v) for v in values[i:i+12]) + ','
                  for i in range(0, len(values), 12)) + '\n}};\n'
text += '} // namespace dobong_source\n'
(OUT / 'dobong_dem_data.h').write_text(text, encoding='utf-8', newline='\n')

sources = ['course-observed.geojson', 'surroundings-source.geojson',
           'terrain/game-dem-129x129.json', 'terrain/manifest.json', 'terrain/validation.json']
manifest = {
    'generator': Path(__file__).name,
    'coordinate_contract': 'Point{x,z}; x=E+52; z=-N-60; terrain y=sourceHeight-baseElevation',
    'course_features': len(course_rows), 'course_vertices': len(course_vertices),
    'course_capture_date': metadata['source_capture_date'],
    'course_source_image': metadata['source_image'],
    'context_features': len(context_rows), 'context_vertices': len(context_vertices),
    'terrain_samples': len(values),
    'source_sha256': {s: hashlib.sha256((ROOT/s).read_bytes()).hexdigest() for s in sources},
    'generated': {name: hashlib.sha256((OUT/name).read_bytes()).hexdigest()
                  for name in ['dobong_observed_data.h', 'dobong_context_data.h', 'dobong_dem_data.h']},
    'warning': 'Source-grounded preview data, not a surveyed/scoring-certified course. Null U features remain without geometry.'
}
(OUT / 'generated-manifest.json').write_text(json.dumps(manifest, indent=2),
                                           encoding='utf-8', newline='\n')
if args.check:
    expected = json.loads((HERE / 'expected-manifest.json').read_text(encoding='utf-8'))
    for key in ('source_sha256', 'generated'):
        if manifest[key] != expected[key]:
            raise SystemExit(f'FAIL: {key} differs from expected-manifest.json')
    print('PASS: 5 source hashes and all 3 generated header hashes match baseline')
else:
    print(json.dumps(manifest, indent=2))
