#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build-web"
OUTPUT_DIR="$BUILD_DIR/dist"
mkdir -p "$OUTPUT_DIR"

emcmake cmake -S "$ROOT_DIR" -B "$BUILD_DIR" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DPLATFORM=Web \
  -DWEB_SHELL_FILE="$ROOT_DIR/web/shell.html" \
  -DWEB_OUTPUT_DIR="$OUTPUT_DIR"
cmake --build "$BUILD_DIR" --config Release

for artifact in index.html index.js index.wasm; do
  if [[ ! -s "$OUTPUT_DIR/$artifact" ]]; then
    printf 'Missing generated artifact: %s\n' "$OUTPUT_DIR/$artifact" >&2
    exit 1
  fi
done

cp "$OUTPUT_DIR/index.html" "$OUTPUT_DIR/index.js" "$OUTPUT_DIR/index.wasm" "$ROOT_DIR/"
if [[ -f "$OUTPUT_DIR/index.data" ]]; then
  cp "$OUTPUT_DIR/index.data" "$ROOT_DIR/"
else
  rm -f "$ROOT_DIR/index.data"
fi

printf '\nBuilt web bundle:\n'
printf '  %s\n' "$ROOT_DIR/index.html" "$ROOT_DIR/index.js" "$ROOT_DIR/index.wasm"
printf 'Shell cache version is generated by CMake for this configuration.\n'
